import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'
import { getAddress, type Address, type Hex } from 'viem'

import { decodeRecipe, deriveDropAddress, encodeRecipe } from './encoding.js'
import { conditionalOrderParamsHash } from './tx.js'

interface Fixtures {
  implementation: Address
  factory: Address
  executor: Address
  proxyCreationCode: Hex
  cases: Array<{ name: string; owner: Address; setupData: Hex; expected: Address }>
  conditionalOrders: Array<{ name: string; handler: Address; salt: Hex; staticInput: Hex; expected: Hex }>
}

const here = dirname(fileURLToPath(import.meta.url))

const fixtures: Fixtures = JSON.parse(
  readFileSync(resolve(here, '../../../contracts/deployments/derivation-fixtures.json'), 'utf8'),
)

/**
 * The SDK derives drop addresses off-chain so a UI can quote one as the user types. That is a
 * second implementation of a formula whose ground truth lives in Solidity, and the failure mode of
 * drift is severe: quoting an address that funds are sent to and then stranded at, because the
 * contract will only ever deploy to the address *it* derives.
 *
 * So the fixtures are generated by calling `DropExecutor.dropOf` on the real compiled contract
 * (contracts/script/Fixtures.s.sol), and checked here.
 */
describe('address derivation matches the contract', () => {
  const deployment = {
    factory: fixtures.factory,
    executor: fixtures.executor,
    shedImplementation: fixtures.implementation,
    proxyCreationCode: fixtures.proxyCreationCode,
  }

  it.each(fixtures.cases.map((c) => [c.name, c] as const))('%s', (_name, testCase) => {
    expect(deriveDropAddress({ deployment, owner: testCase.owner, setupData: testCase.setupData })).toBe(
      getAddress(testCase.expected),
    )
  })

  it('produces a distinct address for every fixture case', () => {
    const derived = fixtures.cases.map((c) =>
      deriveDropAddress({ deployment, owner: c.owner, setupData: c.setupData }),
    )
    expect(new Set(derived).size).toBe(derived.length)
  })
})

/**
 * The fixtures were encoded by Solidity's `abi.encode(Recipe)`. If the SDK's encoder produces the
 * same bytes for the decoded value, the two encoders agree — which is the other half of what makes
 * a recipe file portable.
 */
describe('recipe encoding round-trips against Solidity output', () => {
  it.each(fixtures.cases.map((c) => [c.name, c] as const))('%s', (_name, testCase) => {
    const decoded = decodeRecipe(testCase.setupData)
    expect(encodeRecipe(decoded)).toBe(testCase.setupData.toLowerCase())
  })
})

/**
 * ComposableCoW keys an authorisation by `keccak256(abi.encode(params))`, and a rescue that retires an
 * order has to reproduce that hash off-chain. Checked against the compiled contract for the same reason
 * the address derivation is: two implementations of one formula drift silently, and here the failure
 * mode is a rescue that appears to retire an order and leaves it live.
 */
describe('conditionalOrderParamsHash matches the contract', () => {
  it.each(fixtures.conditionalOrders.map((c) => [c.name, c] as const))('%s', (_name, testCase) => {
    expect(
      conditionalOrderParamsHash({
        handler: testCase.handler,
        salt: testCase.salt,
        staticInput: testCase.staticInput,
      }),
    ).toBe(testCase.expected)
  })
})
