import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'
import { getAddress, type Address, type Hex } from 'viem'

import { decodeRecipe, deriveDropAddress, encodeRecipe } from './encoding.js'
import {
  COW_ORDER_TYPE_HASH,
  hashCowOrder,
  orderUidFor,
  ownerOfOrderUid,
  packOrderUid,
  type CowOrderData,
} from './orderUid.js'
import { decodeDeliveryPayload, encodeDeliveryPayload, type OnFailure } from './bridge.js'
import { conditionalOrderParamsHash } from './tx.js'

interface Fixtures {
  implementation: Address
  factory: Address
  executor: Address
  proxyCreationCode: Hex
  cases: Array<{ name: string; owner: Address; setupData: Hex; expected: Address }>
  conditionalOrders: Array<{ name: string; handler: Address; salt: Hex; staticInput: Hex; expected: Hex }>
  orderUids: Array<{
    name: string
    domainSeparator: Hex
    owner: Address
    /** Serialized by forge, so the numbers arrive as decimal strings. */
    order: Record<keyof CowOrderData, string | boolean>
    digest: Hex
    expected: Hex
  }>
  deliveryPayloads: Array<{ name: string; owner: Address; setupData: Hex; onFailure: OnFailure; expected: Hex }>
}

const here = dirname(fileURLToPath(import.meta.url))

const fixtures: Fixtures = JSON.parse(
  readFileSync(resolve(here, '../../../contracts/deployments/derivation-fixtures.json'), 'utf8'),
)

/**
 * The SDK derives drop addresses off-chain so a UI can quote one as the user types. That is a
 * second implementation of a formula whose ground truth lives in Solidity, and the failure mode of
 * drift is severe: quoting an address that funds are sent to and then stranded at, because the
 * contract will only ever deploy to the address *it* derives.
 *
 * So the fixtures are generated by calling `DropExecutor.dropOf` on the real compiled contract
 * (contracts/script/Fixtures.s.sol), and checked here.
 */
describe('address derivation matches the contract', () => {
  const deployment = {
    factory: fixtures.factory,
    executor: fixtures.executor,
    shedImplementation: fixtures.implementation,
    proxyCreationCode: fixtures.proxyCreationCode,
  }

  it.each(fixtures.cases.map((c) => [c.name, c] as const))('%s', (_name, testCase) => {
    expect(deriveDropAddress({ deployment, owner: testCase.owner, setupData: testCase.setupData })).toBe(
      getAddress(testCase.expected),
    )
  })

  it('produces a distinct address for every fixture case', () => {
    const derived = fixtures.cases.map((c) =>
      deriveDropAddress({ deployment, owner: c.owner, setupData: c.setupData }),
    )
    expect(new Set(derived).size).toBe(derived.length)
  })
})

/**
 * The fixtures were encoded by Solidity's `abi.encode(Recipe)`. If the SDK's encoder produces the
 * same bytes for the decoded value, the two encoders agree — which is the other half of what makes
 * a recipe file portable.
 */
describe('recipe encoding round-trips against Solidity output', () => {
  it.each(fixtures.cases.map((c) => [c.name, c] as const))('%s', (_name, testCase) => {
    const decoded = decodeRecipe(testCase.setupData)
    expect(encodeRecipe(decoded)).toBe(testCase.setupData.toLowerCase())
  })
})

/**
 * ComposableCoW keys an authorisation by `keccak256(abi.encode(params))`, and a rescue that retires an
 * order has to reproduce that hash off-chain. Checked against the compiled contract for the same reason
 * the address derivation is: two implementations of one formula drift silently, and here the failure
 * mode is a rescue that appears to retire an order and leaves it live.
 */
describe('conditionalOrderParamsHash matches the contract', () => {
  it.each(fixtures.conditionalOrders.map((c) => [c.name, c] as const))('%s', (_name, testCase) => {
    expect(
      conditionalOrderParamsHash({
        handler: testCase.handler,
        salt: testCase.salt,
        staticInput: testCase.staticInput,
      }),
    ).toBe(testCase.expected)
  })
})

/**
 * `OrderPlacement` carries no order uid, so the SDK computes one from the order struct and the owner —
 * a second implementation of `LibCowOrder.hash` plus `Orders.packUid`. Checked against the compiled
 * contract for the same reason as everything else here: the drift is silent, and a watch tower checking
 * the pre-signature of a uid no order ever had concludes the order is unsigned and posts nothing.
 */
describe('order hashing matches the contract', () => {
  /** Forge writes the struct as JSON, so widen it back to the types the SDK works in. */
  function orderOf(fixture: Fixtures['orderUids'][number]): CowOrderData {
    const raw = fixture.order
    return {
      sellToken: getAddress(raw.sellToken as string),
      buyToken: getAddress(raw.buyToken as string),
      receiver: getAddress(raw.receiver as string),
      sellAmount: BigInt(raw.sellAmount as string),
      buyAmount: BigInt(raw.buyAmount as string),
      validTo: Number(raw.validTo),
      appData: raw.appData as Hex,
      feeAmount: BigInt(raw.feeAmount as string),
      kind: raw.kind as Hex,
      partiallyFillable: raw.partiallyFillable as boolean,
      sellTokenBalance: raw.sellTokenBalance as Hex,
      buyTokenBalance: raw.buyTokenBalance as Hex,
    }
  }

  describe('hashCowOrder', () => {
    it.each(fixtures.orderUids.map((c) => [c.name, c] as const))('%s', (_name, testCase) => {
      expect(hashCowOrder(orderOf(testCase), testCase.domainSeparator)).toBe(testCase.digest)
    })
  })

  describe('orderUidFor', () => {
    it.each(fixtures.orderUids.map((c) => [c.name, c] as const))('%s', (_name, testCase) => {
      expect(orderUidFor(orderOf(testCase), testCase.owner, testCase.domainSeparator).toLowerCase()).toBe(
        testCase.expected.toLowerCase(),
      )
    })
  })

  describe('ownerOfOrderUid reads back what packOrderUid wrote', () => {
    it.each(fixtures.orderUids.map((c) => [c.name, c] as const))('%s', (_name, testCase) => {
      expect(ownerOfOrderUid(testCase.expected)).toBe(getAddress(testCase.owner))
    })
  })

  it('derives the type hash the settlement contract uses', () => {
    // `LibCowOrder.TYPE_HASH`, hard-coded there and in GPv2. Building it from the type string is what
    // catches declaring `kind` as `bytes32` — plausible, since the struct field is — which yields a
    // digest nothing on-chain has ever signed.
    expect(COW_ORDER_TYPE_HASH).toBe('0xd5a25ba2e97094ad7d83dc28a6572da797d6b3e7fc6663bd93efb789fc17e489')
  })

  it('refuses a validTo that is not a uint32', () => {
    // The uid packs it into four bytes, so a wider number would silently truncate and produce a uid
    // for a different order.
    expect(() => packOrderUid(`0x${'ab'.repeat(32)}`, `0x${'11'.repeat(20)}`, 2 ** 32)).toThrow(/uint32/)
  })
})

/**
 * The bridge delivery payload, encoded on both sides of the wire.
 *
 * The encoding itself is unremarkable — `abi.encode(address, bytes, uint8)` — and that is exactly why
 * it is worth pinning. The `uint8` is a Solidity enum, so its meaning is its declaration order and
 * nothing in the ABI records that. Reordering `DropDelivery.OnFailure` would leave this SDK encoding
 * a number that still decodes and now means the opposite, on a delivery whose money has already
 * crossed a bridge.
 */
describe('delivery payloads match the contract', () => {
  for (const fixture of fixtures.deliveryPayloads) {
    it(fixture.name, () => {
      expect(
        encodeDeliveryPayload({
          owner: fixture.owner,
          setupData: fixture.setupData,
          onFailure: fixture.onFailure,
        }),
      ).toBe(fixture.expected)
    })

    it(`${fixture.name}, decoded back`, () => {
      const decoded = decodeDeliveryPayload(fixture.expected)
      expect(getAddress(decoded.owner)).toBe(getAddress(fixture.owner))
      expect(decoded.setupData).toBe(fixture.setupData)
      expect(decoded.onFailure).toBe(fixture.onFailure)
    })
  }
})
