import {
  concatHex,
  decodeAbiParameters,
  encodeAbiParameters,
  getCreate2Address,
  keccak256,
  hexToString,
  stringToHex,
  type Address,
  type Hex,
} from 'viem'

import type { DropDeployment, Recipe } from './types.js'

/** The default user salt. Recipes carry their own; this is just the common value. */
export const ZERO_SALT: Hex = `0x${'00'.repeat(32)}`

/** The `Call[]` component type, matching cow-shed's `Call` struct. */
const CALL_COMPONENTS = [
  { name: 'target', type: 'address' },
  { name: 'value', type: 'uint256' },
  { name: 'callData', type: 'bytes' },
  { name: 'allowFailure', type: 'bool' },
  { name: 'isDelegateCall', type: 'bool' },
] as const

/** `DropExecutor.Recipe`, as a single dynamic tuple — exactly what `abi.encode(recipe)` produces. */
const RECIPE_ABI = [
  {
    type: 'tuple',
    components: [
      { name: 'label', type: 'bytes32' },
      { name: 'salt', type: 'bytes32' },
      { name: 'once', type: 'bool' },
      { name: 'calls', type: 'tuple[]', components: CALL_COMPONENTS },
    ],
  },
] as const

/** Labels are bytes32, right-padded like a Solidity string literal. */
export function encodeLabel(label: string): Hex {
  const bytes = new TextEncoder().encode(label)
  if (bytes.length > 32) {
    throw new Error(`recipe label must encode to at most 32 bytes, got ${bytes.length}: ${label}`)
  }
  return stringToHex(label, { size: 32 })
}

/** The inverse of `encodeLabel`, with the right padding trimmed back off. */
export function decodeLabel(label: Hex): string {
  return hexToString(label, { size: 32 }).replace(/\0+$/, '')
}

/**
 * Encode a recipe into the `setupData` bytes a drop address commits to.
 *
 * Deterministic by construction: fields are written in a fixed order from parsed values, so the
 * key order or whitespace of whatever JSON the recipe came from cannot influence the result.
 */
export function encodeRecipe(recipe: Recipe): Hex {
  return encodeAbiParameters(RECIPE_ABI, [
    {
      label: encodeLabel(recipe.label),
      salt: recipe.salt,
      once: recipe.once,
      calls: recipe.calls.map((call) => ({
        target: call.target,
        value: call.value,
        callData: call.callData,
        allowFailure: call.allowFailure,
        isDelegateCall: call.isDelegateCall,
      })),
    },
  ])
}

/** Read a recipe back out of the `setupData` its address commits to. The inverse of `encodeRecipe`. */
export function decodeRecipe(setupData: Hex): Recipe {
  const [decoded] = decodeAbiParameters(RECIPE_ABI, setupData)
  return {
    label: decodeLabel(decoded.label),
    salt: decoded.salt,
    once: decoded.once,
    calls: decoded.calls.map((call) => ({
      target: call.target,
      value: call.value,
      callData: call.callData,
      allowFailure: call.allowFailure,
      isDelegateCall: call.isDelegateCall,
    })),
  }
}

/**
 * The user salt carried inside an encoded recipe.
 *
 * Mirrors `DropExecutor._saltOf`. `setupData` is `abi.encode(Recipe)`: one offset word, then
 * `label`, then `salt` — so the salt is the third 32-byte word.
 */
export function saltOf(setupData: Hex): Hex {
  const body = setupData.startsWith('0x') ? setupData.slice(2) : setupData
  if (body.length < 0x60 * 2) {
    throw new Error('setupData is too short to be an encoded recipe')
  }
  return `0x${body.slice(0x40 * 2, 0x60 * 2)}`
}

/**
 * The drop address for an owner and a compiled recipe.
 *
 * Reimplements `COWShedExecutorFactory.proxyOf(owner, executor, salt, executor, setupData)` so a UI
 * can quote an address as the user types, with no RPC round trip. The salt is read back out of
 * `setupData`, exactly as the contract does. The contract remains the ground truth:
 * `derivation.test.ts` checks this against fixtures generated by the deployed code, because a
 * discrepancy here means quoting an address that funds get stranded at.
 */
export function deriveDropAddress(params: {
  deployment: Pick<DropDeployment, 'factory' | 'executor' | 'shedImplementation' | 'proxyCreationCode'>
  owner: Address
  setupData: Hex
}): Address {
  const { deployment, owner, setupData } = params

  // initCode == PROXY_CREATION_CODE ++ abi.encode(implementation, owner) — byte-identical to
  // canonical cow-shed. Only the CREATE2 salt differs between the address schemes.
  const initCodeHash = keccak256(
    concatHex([
      deployment.proxyCreationCode,
      encodeAbiParameters(
        [
          { type: 'address' },
          { type: 'address' },
        ],
        [deployment.shedImplementation, owner],
      ),
    ]),
  )

  const create2Salt = keccak256(
    encodeAbiParameters(
      [
        { type: 'address' },
        { type: 'address' },
        { type: 'bytes32' },
        { type: 'address' },
        { type: 'bytes32' },
      ],
      [owner, deployment.executor, saltOf(setupData), deployment.executor, keccak256(setupData)],
    ),
  )

  return getCreate2Address({ from: deployment.factory, salt: create2Salt, bytecodeHash: initCodeHash })
}
