import {
  concatHex,
  encodeAbiParameters,
  getAddress,
  hashDomain,
  keccak256,
  pad,
  toBytes,
  toHex,
  type Address,
  type Hex,
} from 'viem'

/**
 * GPv2 order hashing and UID packing, off-chain.
 *
 * ## Why this is here at all
 *
 * `ICoWSwapOnchainOrders.OrderPlacement` does not carry an order UID. It carries the order struct,
 * and the owner — in `sender` for a pre-signed order, in `signature.data` for an ERC-1271 one. The UID
 * is `orderDigest ++ owner ++ validTo`, so a consumer that has the struct and the owner has everything
 * it needs and can compute one; the contract emitting the log has no reason to pay to put it there.
 *
 * That decision moves an EIP-712 hash from Solidity to TypeScript, which is a second implementation of
 * a formula whose ground truth is `cow-shed/LibCowOrder.sol`. The failure mode is quiet: a watch tower
 * that checks `preSignature` against a UID no order ever had sees an unsigned order and posts nothing.
 * So `derivation.test.ts` asserts every function here against fixtures generated by the compiled
 * contract — see `contracts/script/Fixtures.s.sol`.
 *
 * Nothing in this module talks to a chain or to CoW.
 */

/**
 * The EIP-712 type of a CoW order, as `GPv2Order` declares it.
 *
 * Hashed from the string rather than hard-coded, so a field added or reordered here changes the type
 * hash the way EIP-712 says it should instead of silently disagreeing with a stale constant.
 *
 * Note `kind`, `sellTokenBalance` and `buyTokenBalance` are declared **`string`** while the struct
 * holds them as `bytes32`. That is not an inconsistency: EIP-712 encodes a `string` as the keccak of
 * its contents, and the constants GPv2 uses — `keccak256("sell")`, `keccak256("erc20")` — are already
 * that hash. So the declared type is `string` and the encoded word is the flag, unchanged. Declaring
 * `bytes32` here instead produces a different type hash and a digest the settlement contract has never
 * heard of, which is a signature that verifies against nothing.
 */
const ORDER_TYPE =
  'Order(address sellToken,address buyToken,address receiver,uint256 sellAmount,uint256 buyAmount,' +
  'uint32 validTo,bytes32 appData,uint256 feeAmount,string kind,bool partiallyFillable,' +
  'string sellTokenBalance,string buyTokenBalance)'

/** `keccak256(ORDER_TYPE)` — `GPv2Order.TYPE_HASH`. */
export const COW_ORDER_TYPE_HASH: Hex = keccak256(toBytes(ORDER_TYPE))

const ORDER_STRUCT_PARAMS = [
  { type: 'bytes32' },
  { type: 'address' },
  { type: 'address' },
  { type: 'address' },
  { type: 'uint256' },
  { type: 'uint256' },
  { type: 'uint32' },
  { type: 'bytes32' },
  { type: 'uint256' },
  { type: 'bytes32' },
  { type: 'bool' },
  { type: 'bytes32' },
  { type: 'bytes32' },
] as const

/** A CoW order, field for field as the settlement contract hashes it. */
export interface CowOrderData {
  sellToken: Address
  buyToken: Address
  receiver: Address
  sellAmount: bigint
  buyAmount: bigint
  validTo: number
  appData: Hex
  feeAmount: bigint
  kind: Hex
  partiallyFillable: boolean
  sellTokenBalance: Hex
  buyTokenBalance: Hex
}

/**
 * `GPv2Settlement.domainSeparator()`, computed rather than fetched.
 *
 * The name and version are the protocol's and have never changed — `Gnosis Protocol` / `v2`, which is
 * why the strings are inlined rather than configurable. Deriving it means a poster needs no `eth_call`
 * before it can decode a log, which matters when the point is to scan a range of blocks.
 */
export function cowDomainSeparator(chainId: number, settlement: Address): Hex {
  return hashDomain({
    domain: { name: 'Gnosis Protocol', version: 'v2', chainId: BigInt(chainId), verifyingContract: settlement },
    types: {
      EIP712Domain: [
        { name: 'name', type: 'string' },
        { name: 'version', type: 'string' },
        { name: 'chainId', type: 'uint256' },
        { name: 'verifyingContract', type: 'address' },
      ],
    },
  })
}

/**
 * The EIP-712 digest the settlement contract identifies `order` by.
 *
 * Mirrors `LibCowOrder.hash`. Takes a domain separator rather than a chain id, so a caller holding one
 * from anywhere — `cowDomainSeparator`, an `eth_call`, ComposableCoW — can use it unchanged.
 */
export function hashCowOrder(order: CowOrderData, domainSeparator: Hex): Hex {
  const structHash = keccak256(
    encodeAbiParameters(ORDER_STRUCT_PARAMS, [
      COW_ORDER_TYPE_HASH,
      order.sellToken,
      order.buyToken,
      order.receiver,
      order.sellAmount,
      order.buyAmount,
      order.validTo,
      order.appData,
      order.feeAmount,
      order.kind,
      order.partiallyFillable,
      order.sellTokenBalance,
      order.buyTokenBalance,
    ]),
  )

  return keccak256(concatHex(['0x1901', domainSeparator, structHash]))
}

/**
 * The 56-byte UID the settlement contract keys a signature and its fills by.
 *
 * `orderDigest ++ owner ++ validTo`, per `GPv2Order.packOrderUidParams`. `validTo` is four big-endian
 * bytes, which is what makes the layout fixed-width and the owner readable at a constant offset.
 */
export function packOrderUid(orderDigest: Hex, owner: Address, validTo: number): Hex {
  if (!Number.isInteger(validTo) || validTo < 0 || validTo > 0xffffffff) {
    throw new Error(`validTo must be a uint32, got ${validTo}`)
  }
  return concatHex([pad(orderDigest, { size: 32 }), getAddress(owner), pad(toHex(validTo), { size: 4 })])
}

/** `packOrderUid`, from the order itself. */
export function orderUidFor(order: CowOrderData, owner: Address, domainSeparator: Hex): Hex {
  return packOrderUid(hashCowOrder(order, domainSeparator), owner, order.validTo)
}

/**
 * The owner encoded in an order UID.
 *
 * A UID is `orderDigest ++ owner ++ validTo` — 32 + 20 + 4 bytes — so the owner sits at a fixed
 * offset and needs no lookup.
 */
export function ownerOfOrderUid(orderUid: Hex): Address {
  const bytes = orderUid.slice(2)
  if (bytes.length !== 112) throw new Error(`order uid must be 56 bytes, got ${bytes.length / 2}`)
  return getAddress(`0x${bytes.slice(64, 104)}`)
}
