import {
  decodeEventLog,
  encodeAbiParameters,
  encodeFunctionData,
  keccak256,
  type Address,
  type Hex,
  type Log,
} from 'viem'

import { DROP_EXECUTOR_ABI, PRESIGN_STEPS_ABI } from './generated/artifacts.js'
import type { DropDeployment } from './types.js'

export interface EvmCall {
  to: Address
  data: Hex
  value: bigint
}

/**
 * The transaction that deploys a drop and runs its recipe — or re-runs it, if the drop already
 * exists. Anyone can send it; there is no signature to collect and no privileged sender, so a
 * keeper, a solver pre-interaction or the user's own wallet are interchangeable here.
 */
export function buildActivateTx(params: {
  deployment: Pick<DropDeployment, 'executor'>
  owner: Address
  setupData: Hex
}): EvmCall {
  return {
    to: params.deployment.executor,
    data: encodeFunctionData({
      abi: DROP_EXECUTOR_ABI,
      functionName: 'activate',
      args: [params.owner, params.setupData],
    }),
    value: 0n,
  }
}

/** A CoW order as emitted by `DropOrderPlaced`. */
export interface PlacedOrder {
  orderUid: Hex
  sellToken: Address
  buyToken: Address
  receiver: Address
  sellAmount: bigint
  buyAmount: bigint
  validTo: number
  appData: Hex
  feeAmount: bigint
  kind: Hex
  partiallyFillable: boolean
  sellTokenBalance: Hex
  buyTokenBalance: Hex
}

/**
 * Decode a `DropOrderPlaced` log into the order that was pre-signed.
 *
 * The event is emitted from inside a delegatecall, so its emitter is the drop rather than
 * `PresignSteps` — which is what lets a poster filter by drop address.
 */
export function parseDropOrderPlaced(log: Pick<Log, 'data' | 'topics'>): PlacedOrder {
  const decoded = decodeEventLog({
    abi: PRESIGN_STEPS_ABI,
    eventName: 'DropOrderPlaced',
    data: log.data,
    topics: log.topics,
  })

  const { orderUid, order } = decoded.args as unknown as {
    orderUid: Hex
    order: {
      sellToken: Address
      buyToken: Address
      receiver: Address
      sellAmount: bigint
      buyAmount: bigint
      validTo: number
      appData: Hex
      feeAmount: bigint
      kind: Hex
      partiallyFillable: boolean
      sellTokenBalance: Hex
      buyTokenBalance: Hex
    }
  }

  return { orderUid, ...order }
}

const KIND_SELL = '0xf3b277728b3fee749481eb3e0b3b48980dbbab78658fc419025cb16eee346775'
const BALANCE_ERC20 = '0x5a28e9363bb942b639270062aa6bb295f434bcdfc42c97267bf003f272060dc9'

/**
 * Turn a placed order into the body for `POST /api/v1/orders`.
 *
 * `signingScheme: 'presign'` tells the order book to check the on-chain pre-signature instead of
 * verifying bytes, and `from` is the drop — the order's owner and the address that signed it.
 */
export function toOrderBookPayload(order: PlacedOrder, drop: Address) {
  return {
    sellToken: order.sellToken,
    buyToken: order.buyToken,
    receiver: order.receiver,
    sellAmount: order.sellAmount.toString(),
    buyAmount: order.buyAmount.toString(),
    validTo: order.validTo,
    appData: order.appData,
    feeAmount: order.feeAmount.toString(),
    kind: order.kind === KIND_SELL ? 'sell' : 'buy',
    partiallyFillable: order.partiallyFillable,
    sellTokenBalance: order.sellTokenBalance === BALANCE_ERC20 ? 'erc20' : 'external',
    buyTokenBalance: order.buyTokenBalance === BALANCE_ERC20 ? 'erc20' : 'internal',
    signingScheme: 'presign' as const,
    // For a pre-signed order the signature field carries the owner, not a signature.
    signature: drop,
    from: drop,
  }
}

/**
 * ComposableCoW's registration event, hand-written for the same reason as the revoke ABI: composable-cow
 * is not a submodule here, so there is no artifact to generate from.
 */
const CONDITIONAL_ORDER_CREATED_ABI = [
  {
    type: 'event',
    name: 'ConditionalOrderCreated',
    inputs: [
      { name: 'owner', type: 'address', indexed: true },
      {
        name: 'params',
        type: 'tuple',
        indexed: false,
        components: [
          { name: 'handler', type: 'address' },
          { name: 'salt', type: 'bytes32' },
          { name: 'staticInput', type: 'bytes' },
        ],
      },
    ],
  },
] as const

/**
 * `keccak256(abi.encode(params))`, the key ComposableCoW stores an authorisation under and the argument
 * `remove` takes.
 *
 * Mirrors `ComposableCoW.hash`. Two implementations of one formula drift silently and the failure mode
 * here is a rescue that appears to retire an order and does not, so it is checked against fixtures
 * generated by the compiled contract — see `derivation.test.ts`.
 */
export function conditionalOrderParamsHash(params: {
  handler: Address
  salt: Hex
  staticInput: Hex
}): Hex {
  return keccak256(
    encodeAbiParameters(
      [
        {
          type: 'tuple',
          components: [
            { name: 'handler', type: 'address' },
            { name: 'salt', type: 'bytes32' },
            { name: 'staticInput', type: 'bytes' },
          ],
        },
      ],
      [params],
    ),
  )
}

/** One conditional order a drop registered, and the hash ComposableCoW keys it by. */
export interface RegisteredConditionalOrder {
  owner: Address
  handler: Address
  salt: Hex
  staticInput: Hex
  /** `keccak256(abi.encode(params))` — what `remove` takes, and what a rescue needs. */
  paramsHash: Hex
}

/**
 * Every conditional order an activation registered, from its receipt.
 *
 * This is what makes a complete rescue possible. The params hash cannot be computed before activation,
 * because it covers the amount that arrived — so the receipt is where it first exists. Keep it with the
 * recipe file: retiring the order later needs it, and nothing on-chain will hand it back in a form the
 * SDK can use.
 */
export function parseConditionalOrdersCreated(
  logs: readonly Pick<Log, 'data' | 'topics' | 'address'>[],
  composableCow: Address,
): RegisteredConditionalOrder[] {
  const found: RegisteredConditionalOrder[] = []

  for (const log of logs) {
    if (log.address?.toLowerCase() !== composableCow.toLowerCase()) continue

    let decoded
    try {
      decoded = decodeEventLog({
        abi: CONDITIONAL_ORDER_CREATED_ABI,
        eventName: 'ConditionalOrderCreated',
        data: log.data,
        topics: log.topics,
      })
    } catch {
      // Some other ComposableCoW event in the same transaction.
      continue
    }

    const { owner, params } = decoded.args as unknown as {
      owner: Address
      params: { handler: Address; salt: Hex; staticInput: Hex }
    }

    found.push({
      owner,
      handler: params.handler,
      salt: params.salt,
      staticInput: params.staticInput,
      paramsHash: conditionalOrderParamsHash(params),
    })
  }

  return found
}
